#!/bin/bash
echo "=== UPTIME MONITORING SETUP ==="
echo ""
echo "Step 1: Go to https://uptimerobot.com"
echo "Step 2: Create free account"
echo "Step 3: Add New Monitor:"
echo "  Type: HTTP(s)"
echo "  Friendly Name: CINEOS API"
echo "  URL: https://cinerisk-api-production.up.railway.app/v1/health"
echo "  Monitoring Interval: Every 5 minutes"
echo "  Alert Contacts: yugandhar@cineos.in"
echo ""
echo "Step 4: Add second monitor:"
echo "  Type: HTTP(s)"
echo "  Friendly Name: CINEOS Website"
echo "  URL: https://dbayugandhar-cmyk.github.io/cinerisk-api/cineos_landing.html"
echo "  Monitoring Interval: Every 5 minutes"
echo ""
echo "After setup you can say:"
echo "  'CINEOS API is monitored 24/7 by UptimeRobot'"
echo "  'We receive immediate email alerts on any downtime'"
echo "  '99.9% uptime SLA — verified by third-party monitoring'"
echo ""
echo "Free tier: 50 monitors, 5-min interval, email alerts"
echo "Status page URL (public): share with partners"
